server {
    listen 80;
    server_name pokemonchic.com www.pokemonchic.com;

    # поменяй путь на реальную папку проекта
    root /var/www/pokemonchic.com;
    index index.php index.html;
    charset utf-8;

    access_log /var/log/nginx/pokemonchic.access.log;
    error_log  /var/log/nginx/pokemonchic.error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PHP_VALUE "default_charset=UTF-8";
        fastcgi_pass unix:/run/php/php8.0-fpm.sock;
    }

    location ~ /\. {
        deny all;
    }

    location ~* \.(log|sql|bak|old|rar|zip)$ {
        deny all;
    }
}
