-- Metadata for special Pokemon forms.
-- Keeps public dex numbering separate from internal battle/base ids.

CREATE TABLE IF NOT EXISTS pokemon_forms (
    form_id INT NOT NULL,
    base_id INT NOT NULL,
    form_key VARCHAR(32) NOT NULL,
    form_title VARCHAR(64) NOT NULL,
    is_battle_form TINYINT NOT NULL DEFAULT 1,
    created_at INT NOT NULL DEFAULT 0,
    updated_at INT NOT NULL DEFAULT 0,
    PRIMARY KEY (form_id),
    KEY idx_pokemon_forms_base (base_id, form_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO pokemon_forms (form_id, base_id, form_key, form_title, is_battle_form, created_at, updated_at)
VALUES
    (5000,1,'mega','Mega Venusaur',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5001,6,'mega_y','Mega Charizard Y',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5002,6,'mega_x','Mega Charizard X',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5003,9,'mega','Mega Blastoise',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5004,65,'mega','Mega Alakazam',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5005,94,'mega','Mega Gengar',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5006,115,'mega','Mega Kangaskhan',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5007,127,'mega','Mega Pinsir',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5008,130,'mega','Mega Gyarados',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5009,142,'mega','Mega Aerodactyl',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5010,150,'mega_x','Mega Mewtwo X',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5011,150,'mega_y','Mega Mewtwo Y',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5012,181,'mega','Mega Ampharos',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5013,212,'mega','Mega Scizor',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5014,214,'mega','Mega Heracross',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5015,229,'mega','Mega Houndoom',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5016,248,'mega','Mega Tyranitar',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5017,382,'primal','Primal Kyogre',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5018,383,'primal','Primal Groudon',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5019,384,'mega','Mega Rayquaza',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5020,15,'mega','Mega Beedrill',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5021,18,'mega','Mega Pidgeot',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5022,80,'mega','Mega Slowbro',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5023,208,'mega','Mega Steelix',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5024,254,'mega','Mega Sceptile',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5025,257,'mega','Mega Blaziken',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5026,260,'mega','Mega Swampert',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5027,282,'mega','Mega Gardevoir',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5028,302,'mega','Mega Sableye',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5029,303,'mega','Mega Mawile',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5030,306,'mega','Mega Aggron',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5031,308,'mega','Mega Medicham',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5032,310,'mega','Mega Manectric',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5033,319,'mega','Mega Sharpedo',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5034,323,'mega','Mega Camerupt',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5035,334,'mega','Mega Altaria',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5036,354,'mega','Mega Banette',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5037,359,'mega','Mega Absol',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5038,362,'mega','Mega Glalie',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5039,373,'mega','Mega Salamence',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5040,376,'mega','Mega Metagross',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5041,380,'mega','Mega Latias',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5042,381,'mega','Mega Latios',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5043,428,'mega','Mega Lopunny',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5044,445,'mega','Mega Garchomp',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5045,448,'mega','Mega Lucario',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5046,460,'mega','Mega Abomasnow',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5047,475,'mega','Mega Gallade',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5048,531,'mega','Mega Audino',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    (5049,719,'mega','Mega Diancie',1,UNIX_TIMESTAMP(),UNIX_TIMESTAMP())
ON DUPLICATE KEY UPDATE
    base_id = VALUES(base_id),
    form_key = VALUES(form_key),
    form_title = VALUES(form_title),
    is_battle_form = VALUES(is_battle_form),
    updated_at = UNIX_TIMESTAMP();

CREATE TABLE IF NOT EXISTS pokemon_ability_descriptions (
    ability_key VARCHAR(64) NOT NULL,
    name_ru VARCHAR(96) NOT NULL,
    description_ru TEXT NOT NULL,
    created_at INT NOT NULL DEFAULT 0,
    updated_at INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ability_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO pokemon_ability_descriptions (ability_key, name_ru, description_ru, created_at, updated_at)
VALUES
    ('adaptability','Адаптивность','Усиливает бонус STAB: атаки своего типа получают больший прирост урона.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('aerilate','Аэрилейт','Атаки Normal-типа становятся Flying-типом и получают дополнительный бонус силы.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('delta_stream','Дельта-поток','При выходе вызывает Сильный ветер: он перекрывает обычную и праймал-погоду и ослабляет атаки, особенно опасные для Flying-типа.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('desolate_land','Выжженная земля','При выходе вызывает Жаркое солнце: действуют эффекты солнца, атаки Water-типа не выполняются.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('drought','Засуха','При выходе вызывает солнечную погоду.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('filter','Фильтр','Ослабляет урон от суперэффективных атак.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('healer','Целитель','Может снять негативный статус союзника в командном бою.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('huge_power','Огромная сила','Значительно повышает физическую атаку покемона.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('inner_focus','Внутренний фокус','Покемон не вздрагивает от эффектов, заставляющих пропустить ход.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('insomnia','Бессонница','Покемон не может уснуть.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('intimidate','Запугивание','При выходе снижает атаку противника.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('levitate','Левитация','Даёт иммунитет к Ground-атакам и части наземных ловушек.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('lightning_rod','Громоотвод','Перенаправляет Electric-атаки и повышает специальную атаку.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('magic_bounce','Магическое зеркало','Отражает часть статусных атак и ловушек обратно в противника.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('mega_launcher','Мега-лаунчер','Усиливает пульсовые и аурные атаки.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('mold_breaker','Разрушитель форм','Атаки игнорируют часть защитных способностей цели.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('no_guard','Без защиты','Атаки обоих покемонов попадают без проверки точности, если ход разрешён.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('parental_bond','Родительская связь','Атакующий удар наносится повторно ослабленным вторым попаданием.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('pixilate','Пиксилейт','Атаки Normal-типа становятся Fairy-типом и получают дополнительный бонус силы.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('prankster','Шутник','Статусные атаки получают повышенный приоритет.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('primordial_sea','Первозданное море','При выходе вызывает Сильный ливень: действуют эффекты дождя, атаки Fire-типа не выполняются.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('pure_power','Чистая сила','Значительно повышает физическую атаку покемона.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('refrigerate','Рефрижерация','Атаки Normal-типа становятся Ice-типом и получают дополнительный бонус силы.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('sand_force','Сила песка','В песчаную бурю усиливает Steel, Rock и Ground-атаки.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('sand_stream','Песчаный поток','При выходе вызывает песчаную бурю.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('scrappy','Задира','Позволяет Normal и Fighting-атакам попадать по Ghost-целям.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('shadow_tag','Теневая ловушка','Противник не может свободно заменить покемона.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('sheer_force','Грубая сила','Усиливает атаки с дополнительными эффектами, но убирает эти дополнительные эффекты.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('shell_armor','Панцирь','Защищает от критических ударов.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('skill_link','Связующее звено','Многоударные атаки всегда попадают максимальное число раз.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('snow_warning','Снежное предупреждение','При выходе вызывает град.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('solar_power','Солнечная батарея','В солнечную погоду повышает специальную атаку, но покемон теряет HP каждый раунд.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('speed_boost','Ускорение','В конце каждого раунда повышает скорость.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('steadfast','Стойкость','Если покемон вздрогнул, его скорость повышается.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('swift_swim','Плавание','В дождь скорость покемона удваивается.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('technician','Техник','Усиливает слабые атаки.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('thick_fat','Толстый жир','Снижает урон от Fire и Ice-атак.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('tough_claws','Крепкие когти','Усиливает контактные атаки.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),
    ('trace','Копирование','При выходе копирует способность противника.',UNIX_TIMESTAMP(),UNIX_TIMESTAMP())
ON DUPLICATE KEY UPDATE
    name_ru = VALUES(name_ru),
    description_ru = VALUES(description_ru),
    updated_at = UNIX_TIMESTAMP();
