<?php
  $name = 'Р вЂќР С•РЎР‚Р С•Р С–Р В° 3';
  $about = 'Р С›РЎвЂљР Т‘Р В°Р В»РЎРЏРЎРЏРЎРѓРЎРЉ Р С•РЎвЂљ Р С—РЎР‚Р ВµР С”РЎР‚Р В°РЎРѓР Р…Р С•Р С–Р С• Р С•Р В·Р ВµРЎР‚Р В°, Р Р†РЎвЂ№ Р С‘Р Т‘РЎвЂРЎвЂљР Вµ Р С—Р С• РЎвЂљРЎР‚Р С•Р С—Р Вµ, Р С”Р С•РЎвЂљР С•РЎР‚Р В°РЎРЏ Р Р†Р ВµР Т‘РЎвЂРЎвЂљ Р Р†Р В°РЎРѓ Р С” РЎРѓР С”Р В°Р В»Р В°Р С Р С™Р В°Р Р…РЎвЂљР С•. 
            Р вЂњР С•Р Р†Р С•РЎР‚РЎРЏРЎвЂљ, РЎвЂЎРЎвЂљР С• Р В·Р В° РЎРѓР С”Р В°Р В»Р В°Р СР С‘ Р ВµРЎРѓРЎвЂљРЎРЉ Р С—РЎР‚Р ВµР С”РЎР‚Р В°РЎРѓР Р…Р С•Р Вµ Р СР ВµРЎРѓРЎвЂљР С•, Р С–Р Т‘Р Вµ Р СР С•Р В¶Р Р…Р С• РЎР‚Р В°РЎРѓРЎРѓР В»Р В°Р В±Р С‘РЎвЂљРЎРЉРЎРѓРЎРЏ Р С‘ Р С•РЎвЂљР Т‘Р С•РЎвЂ¦Р Р…РЎС“РЎвЂљРЎРЉ, Р Р…Р С• РЎРЊРЎвЂљР С• Р СР ВµРЎРѓРЎвЂљР С• Р Р…Р Вµ Р С•РЎвЂЎР ВµР Р…РЎРЉ Р В±Р ВµР В·Р С•Р С—Р В°РЎРѓР Р…Р С• Р С‘Р В·-Р В·Р В° Р С”Р В°Р СР Р…Р ВµР С—Р В°Р Т‘Р С•Р Р†.';  
  $pers = '...';
  $move = '<a href="/game.php?go=charWork&loc=11" data-go="charWork" data-params="loc=11">Р СњР ВµР В±Р С•Р В»РЎРЉРЎв‚¬Р С•Р Вµ Р С•Р В·Р ВµРЎР‚Р С•</a> 
           | 
           <a href="/game.php?go=charWork&loc=13" data-go="charWork" data-params="loc=13">Р РЋР С”Р В°Р В»РЎвЂ№</a>';
  $img_r = '<img src="img/room/012.png" width="290" height="150">';
?>
<script type="text/javascript"> (function (w, d) { function ajaxGET(url, cb){var x=new XMLHttpRequest();x.open('GET',url,true); try{x.setRequestHeader('X-Requested-With','XMLHttpRequest');}catch(e){} x.onreadystatechange=function(){if(x.readyState===4){var r=null;try{r=JSON.parse(x.responseText);}catch(e){}cb(r,x.status);}}; x.send(null); } function sameOrigin(url){var a=d.createElement('a');a.href=url;return a.host===w.location.host;} function quickGo(href){ w.location.replace(href); } d.addEventListener('click', function(e){ if (e.defaultPrevented || e.button!==0 || e.metaKey||e.ctrlKey||e.shiftKey||e.altKey) return; var a=e.target; while(a && a.tagName!=='A') a=a.parentNode; if(!a||!a.getAttribute) return; var href=a.getAttribute('href')||''; if(!href) return; if(!sameOrigin(href)) return; if (!/\/game\.php\?/.test(href)) return; if (/\bgo=charWork\b/i.test(href)) { e.preventDefault ? e.preventDefault() : (e.returnValue=false); var url = href + (href.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url, function(r){ if (r && r.ok && r.redirect) quickGo(r.redirect); else quickGo('/game.php?go=map'); }); return; } if (/\bgo=map\b/i.test(href) && (/\bgets=/.test(href) || /\bnapadenie=/.test(href))) { e.preventDefault ? e.preventDefault() : (e.returnValue=false); var url2 = href + (href.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url2, function(r){ quickGo('/game.php?go=map'); }); return; } }, true); var _orig_loc = w.loc; function _loc(u){ if (typeof u!=='string'){ if(_orig_loc) try{_orig_loc(u);}catch(e){} return; } if (/^charWork(\b|&)/i.test(u) || /\bgo=charWork\b/i.test(u)){ var full = /^go=/.test(u) ? ('/game.php?'+u) : ('/game.php?go='+u); var url = full + (full.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url, function(r){ if(r&&r.ok&&r.redirect) quickGo(r.redirect); else quickGo('/game.php?go=map'); }); return; } quickGo(/^go=/.test(u)?('/game.php?'+u):('/game.php?go='+u)); } w.loc = _loc; try{ if(w.parent) w.parent.loc = _loc; }catch(e){} try{ if(w.top) w.top.loc=_loc; }catch(e){} })(window, document); </script>
