<?php
$name = 'Р вЂњР С•РЎР‚Р Р…РЎвЂ№Р в„– Р С—Р ВµРЎР‚Р ВµР Р†Р В°Р В»';
$about = 'Р вЂ™РЎвЂ№ Р С—Р С•Р Т‘Р С•РЎв‚¬Р В»Р С‘ Р С” РЎвЂљР В°Р В±Р В»Р С‘РЎвЂЎР С”Р Вµ, Р С—Р С•Р С”РЎР‚РЎвЂ№РЎвЂљР С•Р в„– РЎР‚Р В¶Р В°Р Р†РЎвЂЎР С‘Р Р…Р С•Р в„–. 
          Р С™РЎР‚Р В°РЎРѓР С”Р В° РЎРѓ Р Р…Р ВµРЎвЂ Р С—Р С•РЎвЂЎРЎвЂљР С‘ РЎРѓРЎвЂљР ВµРЎР‚Р В»Р В°РЎРѓРЎРЉ, Р Р…Р С• Р Р†РЎРѓРЎвЂ Р ВµРЎвЂ°Р Вµ Р СР С•Р В¶Р Р…Р С• РЎР‚Р В°Р В·Р С–Р В»РЎРЏР Т‘Р ВµРЎвЂљРЎРЉ Р Р…Р В°Р Т‘Р С—Р С‘РЎРѓРЎРЉ: "Р С›РЎРѓРЎвЂљР С•РЎР‚Р С•Р В¶Р Р…Р С•! Р вЂќР С•РЎР‚Р С•Р С–Р В° Р В·Р В°Р С”РЎР‚РЎвЂ№РЎвЂљР В° Р С‘Р В·-Р В·Р В° РЎРѓР С‘Р В»РЎРЉР Р…Р С•Р С–Р С• Р С”Р В°Р СР Р…Р ВµР С—Р В°Р Т‘Р В°". 
          Р Р€ Р Р†Р В°РЎРѓ Р ВµРЎРѓРЎвЂљРЎРЉ Р Т‘Р Р†Р В° Р Р†Р В°РЎР‚Р С‘Р В°Р Р…РЎвЂљР В° - РЎС“Р в„–РЎвЂљР С‘ Р Р…Р В°Р В·Р В°Р Т‘ Р С‘Р В»Р С‘ Р С—РЎР‚Р С•Р Т‘Р С•Р В»Р В¶Р С‘РЎвЂљРЎРЉ Р С—РЎС“РЎвЂљРЎРЉ Р Р†Р С—Р ВµРЎР‚Р ВµР Т‘...';
$pers = '...';

// Р С›Р В±Р Р…Р С•Р Р†Р В»РЎвЂР Р…Р Р…РЎвЂ№Р Вµ Р С—Р ВµРЎР‚Р ВµРЎвЂ¦Р С•Р Т‘РЎвЂ№ Р В±Р ВµР В· target, РЎРѓ data-* Р В°РЎвЂљРЎР‚Р С‘Р В±РЎС“РЎвЂљР В°Р СР С‘ Р Т‘Р В»РЎРЏ AJAX-Р С•Р В±РЎР‚Р В°Р В±Р С•РЎвЂљР С”Р С‘
$move = '
  <a href="/game.php?go=charWork&loc=13" data-go="charWork" data-params="loc=13">Р РЋР С”Р В°Р В»РЎвЂ№</a> | 
  <a href="/game.php?go=charWork&loc=41" data-go="charWork" data-params="loc=41">Р С’РЎР‚РЎвЂ¦Р ВµР С•Р В»Р С•Р С–Р С‘РЎвЂЎР ВµРЎРѓР С”Р В°РЎРЏ Р С—Р ВµРЎвЂ°Р ВµРЎР‚Р В°</a> | 
  <a href="/game.php?go=charWork&loc=15" data-go="charWork" data-params="loc=15">Р вЂќР С•РЎР‚Р С•Р С–Р В° Р С” Р Р†Р ВµРЎР‚РЎв‚¬Р С‘Р Р…Р Вµ</a> | 
  <a href="/game.php?go=charWork&loc=18" data-go="charWork" data-params="loc=18">Р СџРЎРЉРЎР‹РЎвЂљР ВµРЎР‚</a>';

$img_r = '<img src="img/room/014.png" width="290" height="150">';
?>
<script type="text/javascript"> (function (w, d) { function ajaxGET(url, cb){var x=new XMLHttpRequest();x.open('GET',url,true); try{x.setRequestHeader('X-Requested-With','XMLHttpRequest');}catch(e){} x.onreadystatechange=function(){if(x.readyState===4){var r=null;try{r=JSON.parse(x.responseText);}catch(e){}cb(r,x.status);}}; x.send(null); } function sameOrigin(url){var a=d.createElement('a');a.href=url;return a.host===w.location.host;} function quickGo(href){ w.location.replace(href); } d.addEventListener('click', function(e){ if (e.defaultPrevented || e.button!==0 || e.metaKey||e.ctrlKey||e.shiftKey||e.altKey) return; var a=e.target; while(a && a.tagName!=='A') a=a.parentNode; if(!a||!a.getAttribute) return; var href=a.getAttribute('href')||''; if(!href) return; if(!sameOrigin(href)) return; if (!/\/game\.php\?/.test(href)) return; if (/\bgo=charWork\b/i.test(href)) { e.preventDefault ? e.preventDefault() : (e.returnValue=false); var url = href + (href.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url, function(r){ if (r && r.ok && r.redirect) quickGo(r.redirect); else quickGo('/game.php?go=map'); }); return; } if (/\bgo=map\b/i.test(href) && (/\bgets=/.test(href) || /\bnapadenie=/.test(href))) { e.preventDefault ? e.preventDefault() : (e.returnValue=false); var url2 = href + (href.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url2, function(r){ quickGo('/game.php?go=map'); }); return; } }, true); var _orig_loc = w.loc; function _loc(u){ if (typeof u!=='string'){ if(_orig_loc) try{_orig_loc(u);}catch(e){} return; } if (/^charWork(\b|&)/i.test(u) || /\bgo=charWork\b/i.test(u)){ var full = /^go=/.test(u) ? ('/game.php?'+u) : ('/game.php?go='+u); var url = full + (full.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url, function(r){ if(r&&r.ok&&r.redirect) quickGo(r.redirect); else quickGo('/game.php?go=map'); }); return; } quickGo(/^go=/.test(u)?('/game.php?'+u):('/game.php?go='+u)); } w.loc = _loc; try{ if(w.parent) w.parent.loc = _loc; }catch(e){} try{ if(w.top) w.top.loc=_loc; }catch(e){} })(window, document); </script>
