<?php
$in666 = qInfo(666,'process');
  if(!empty($_GET['npc']) && ($_GET['npc'] == 1 || $_GET['npc'] == 2 || $_GET['npc'] == 3 || $_GET['npc'] == 4)){
        if ($_GET['npc'] == 1){
            include ("npc/1.php"); 
            $img_r = '<img src="img/room/1_1.png" width="250" height="150">';
        }
        elseif ($_GET['npc'] == 2) include ("npc/shop.php");
        elseif ($_GET['npc'] == 3) include ("npc/shop_rod.php");
  }else{ 
    $name = 'Р вЂ™Р ВµРЎР‚РЎвЂљР В°Р Р…Р С‘РЎРЏ';
    $about = 'Р вЂ™Р ВµРЎР‚РЎвЂљР В°Р Р…Р С‘РЎРЏ - РЎРЊРЎвЂљР С• Р Р…Р ВµР В±Р С•Р В»РЎРЉРЎв‚¬Р С•Р в„– Р С–Р С•РЎР‚Р С•Р Т‘, РЎРѓР С•РЎРѓРЎвЂљР С•РЎРЏРЎвЂ°Р С‘Р в„– Р Р†РЎРѓР ВµР С–Р С• Р С‘Р В· Р С—Р В°РЎР‚РЎвЂ№ Р Т‘Р С•Р СР С•Р Р†, Р В±Р С•Р В»РЎРЉРЎв‚¬Р С•Р С–Р С• Р С—Р С•Р С”Р ВµРЎвЂ Р ВµР Р…РЎвЂљРЎР‚Р В° Р С‘ Р В·Р В°Р В±РЎР‚Р С•РЎв‚¬Р ВµР Р…Р Р…Р С•Р в„– РЎв‚¬Р В°РЎвЂ¦РЎвЂљРЎвЂ№. 
              Р ВР В·-Р В·Р В° РЎРѓР Р†Р С•Р С‘РЎвЂ¦ Р СР ВµР В»Р С”Р С‘РЎвЂ¦ РЎР‚Р В°Р В·Р СР ВµРЎР‚Р С•Р Р†, Р С–Р С•РЎР‚Р С•Р Т‘ Р Т‘Р С•Р В»Р С–Р С•Р Вµ Р Р†РЎР‚Р ВµР СРЎРЏ Р Р…Р Вµ Р С‘Р СР ВµР В» Р С—РЎР‚Р В°Р Р†Р В° Р В·Р В°Р Р†Р С•Р Т‘Р С‘РЎвЂљРЎРЉ РЎРѓР Р†Р С•Р в„– РЎРѓРЎвЂљР В°Р Т‘Р С‘Р С•Р Р…, Р Р…Р С• РЎРѓР С•Р Р†РЎРѓР ВµР С Р Р…Р ВµР Т‘Р В°Р Р†Р Р…Р С• Р Р…Р В° РЎРЊРЎвЂљР С• Р В±РЎвЂ№Р В»Р С• Р Т‘Р В°Р Р…Р С• РЎР‚Р В°Р В·РЎР‚Р ВµРЎв‚¬Р ВµР Р…Р С‘Р Вµ.';  
    $pers = '<a href="/game.php?go=char&npc=1&do_npc=pc">Р СџР С•Р С”Р ВµРЎвЂ Р ВµР Р…РЎвЂљРЎР‚</a> | <a href="/game.php?go=char&npc=2">Р СџР С•Р С”Р ВµР СР В°РЎР‚Р С”Р ВµРЎвЂљ</a> | <a href="/game.php?go=char&npc=3">Р СџРЎР‚Р С•Р Т‘Р В°Р Р†Р ВµРЎвЂ  РЎС“Р Т‘Р С•РЎвЂЎР ВµР С”</a> ';
    $move = '<a href="/game.php?go=charWork&loc=5" target="_chat_two">Р вЂєР ВµРЎРѓ Р вЂ™Р ВµРЎР‚РЎвЂљР В°Р Р…Р С‘Р С‘</a> | <a href="/game.php?go=charWork&loc=82" target="_chat_two">Р РЋРЎвЂљР В°Р Т‘Р С‘Р С•Р Р… Р СћРЎР‚Р В°Р Р†РЎРЏР Р…РЎвЂ№РЎвЂ¦ Р С—Р С•Р С”Р ВµР СР С•Р Р…Р С•Р Р†</a>';
  }
?>
<script type="text/javascript"> (function (w, d) { function ajaxGET(url, cb){var x=new XMLHttpRequest();x.open('GET',url,true); try{x.setRequestHeader('X-Requested-With','XMLHttpRequest');}catch(e){} x.onreadystatechange=function(){if(x.readyState===4){var r=null;try{r=JSON.parse(x.responseText);}catch(e){}cb(r,x.status);}}; x.send(null); } function sameOrigin(url){var a=d.createElement('a');a.href=url;return a.host===w.location.host;} function quickGo(href){ w.location.replace(href); } d.addEventListener('click', function(e){ if (e.defaultPrevented || e.button!==0 || e.metaKey||e.ctrlKey||e.shiftKey||e.altKey) return; var a=e.target; while(a && a.tagName!=='A') a=a.parentNode; if(!a||!a.getAttribute) return; var href=a.getAttribute('href')||''; if(!href) return; if(!sameOrigin(href)) return; if (!/\/game\.php\?/.test(href)) return; if (/\bgo=charWork\b/i.test(href)) { e.preventDefault ? e.preventDefault() : (e.returnValue=false); var url = href + (href.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url, function(r){ if (r && r.ok && r.redirect) quickGo(r.redirect); else quickGo('/game.php?go=map'); }); return; } if (/\bgo=map\b/i.test(href) && (/\bgets=/.test(href) || /\bnapadenie=/.test(href))) { e.preventDefault ? e.preventDefault() : (e.returnValue=false); var url2 = href + (href.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url2, function(r){ quickGo('/game.php?go=map'); }); return; } }, true); var _orig_loc = w.loc; function _loc(u){ if (typeof u!=='string'){ if(_orig_loc) try{_orig_loc(u);}catch(e){} return; } if (/^charWork(\b|&)/i.test(u) || /\bgo=charWork\b/i.test(u)){ var full = /^go=/.test(u) ? ('/game.php?'+u) : ('/game.php?go='+u); var url = full + (full.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url, function(r){ if(r&&r.ok&&r.redirect) quickGo(r.redirect); else quickGo('/game.php?go=map'); }); return; } quickGo(/^go=/.test(u)?('/game.php?'+u):('/game.php?go='+u)); } w.loc = _loc; try{ if(w.parent) w.parent.loc = _loc; }catch(e){} try{ if(w.top) w.top.loc=_loc; }catch(e){} })(window, document); </script>
