<?php  

    $name = 'Р вЂќР С•РЎР‚Р С•Р С–Р В° 4';
    $about = 'Р вЂ™РЎвЂ№ Р С—Р С•Р С”Р С‘Р Т‘Р В°Р ВµРЎвЂљР Вµ Р СџРЎРЉРЎР‹РЎвЂљР ВµРЎР‚ Р С‘ Р Р…Р В°Р С—РЎР‚Р В°Р Р†Р В»РЎРЏР ВµРЎвЂљР ВµРЎРѓРЎРЉ Р С” Р С—РЎР‚Р ВµР С”РЎР‚Р В°РЎРѓР Р…Р С•Р СРЎС“ Р С–Р С•РЎР‚Р С•Р Т‘РЎС“ Р В¦Р ВµРЎР‚РЎС“Р В»Р С‘Р Р…. 
              Р СџРЎР‚Р С•РЎвЂ¦Р С•Р Т‘РЎРЏ Р С—Р С• Р С”Р В°Р СР ВµР Р…Р Р…Р С•Р в„– Р Т‘Р С•РЎР‚Р С•Р С–Р Вµ, Р вЂ™РЎвЂ№ Р В·Р В°Р СР ВµРЎвЂЎР В°Р ВµРЎвЂљР Вµ РЎвЂљР В°Р В±Р В»Р С‘РЎвЂЎР С”РЎС“ РЎРѓ Р Р…Р В°Р Т‘Р С—Р С‘РЎРѓРЎРЉРЎР‹ - "Р В¦Р ВµРЎР‚РЎС“Р В»Р С‘Р Р… - 2Р С”Р С". 
              Р СџРЎР‚Р С•Р в„–Р Т‘РЎРЏ РЎС“Р С”Р В°Р В·Р В°РЎвЂљР ВµР В»РЎРЉ, Р Р†Р Т‘Р В°Р В»Р ВµР С”Р Вµ, Р вЂ™РЎвЂ№ Р В·Р В°Р СР ВµРЎвЂЎР В°Р ВµРЎвЂљР Вµ Р Р…Р ВµР В±Р С•Р В»РЎРЉРЎв‚¬Р С•Р в„– Р СР С•РЎРѓРЎвЂљ РЎвЂЎР ВµРЎР‚Р ВµР В· РЎР‚Р ВµР С”РЎС“.';
    $pers = '...';
    $move = '<a href="/game.php?go=charWork&loc=18" target="_chat_two">Р СџРЎРЉРЎР‹РЎвЂљР ВµРЎР‚</a> | 
             <a href="/game.php?go=charWork&loc=21" target="_chat_two">Р СљР С•РЎРѓРЎвЂљ</a>
             ';

?>
<script type="text/javascript"> (function (w, d) { function ajaxGET(url, cb){var x=new XMLHttpRequest();x.open('GET',url,true); try{x.setRequestHeader('X-Requested-With','XMLHttpRequest');}catch(e){} x.onreadystatechange=function(){if(x.readyState===4){var r=null;try{r=JSON.parse(x.responseText);}catch(e){}cb(r,x.status);}}; x.send(null); } function sameOrigin(url){var a=d.createElement('a');a.href=url;return a.host===w.location.host;} function quickGo(href){ w.location.replace(href); } d.addEventListener('click', function(e){ if (e.defaultPrevented || e.button!==0 || e.metaKey||e.ctrlKey||e.shiftKey||e.altKey) return; var a=e.target; while(a && a.tagName!=='A') a=a.parentNode; if(!a||!a.getAttribute) return; var href=a.getAttribute('href')||''; if(!href) return; if(!sameOrigin(href)) return; if (!/\/game\.php\?/.test(href)) return; if (/\bgo=charWork\b/i.test(href)) { e.preventDefault ? e.preventDefault() : (e.returnValue=false); var url = href + (href.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url, function(r){ if (r && r.ok && r.redirect) quickGo(r.redirect); else quickGo('/game.php?go=map'); }); return; } if (/\bgo=map\b/i.test(href) && (/\bgets=/.test(href) || /\bnapadenie=/.test(href))) { e.preventDefault ? e.preventDefault() : (e.returnValue=false); var url2 = href + (href.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url2, function(r){ quickGo('/game.php?go=map'); }); return; } }, true); var _orig_loc = w.loc; function _loc(u){ if (typeof u!=='string'){ if(_orig_loc) try{_orig_loc(u);}catch(e){} return; } if (/^charWork(\b|&)/i.test(u) || /\bgo=charWork\b/i.test(u)){ var full = /^go=/.test(u) ? ('/game.php?'+u) : ('/game.php?go='+u); var url = full + (full.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url, function(r){ if(r&&r.ok&&r.redirect) quickGo(r.redirect); else quickGo('/game.php?go=map'); }); return; } quickGo(/^go=/.test(u)?('/game.php?'+u):('/game.php?go='+u)); } w.loc = _loc; try{ if(w.parent) w.parent.loc = _loc; }catch(e){} try{ if(w.top) w.top.loc=_loc; }catch(e){} })(window, document); </script>
