<?php  
    $name = 'Р СљР С•РЎРѓРЎвЂљ';
    $about = 'Р РЋР С•Р Р†РЎРѓР ВµР С Р Р…Р С•Р Р†РЎвЂ№Р в„– Р СР С•РЎРѓРЎвЂљ, Р С”Р С•РЎвЂљР С•РЎР‚РЎвЂ№Р в„–, Р С—Р С•-Р Р†Р С‘Р Т‘Р С‘Р СР С•Р СРЎС“, Р С—Р С•РЎРѓРЎвЂљР В°Р Р†Р С‘Р В»Р С‘ РЎРѓР С•Р Р†РЎРѓР ВµР С Р Р…Р ВµР Т‘Р В°Р Р†Р Р…Р С•. 
              Р вЂ™РЎвЂ№ Р С•Р С–Р В»РЎРЏР Т‘РЎвЂ№Р Р†Р В°Р ВµРЎвЂљР ВµРЎРѓРЎРЉ Р Р†Р Р…Р С‘Р В· Р С‘ РЎРѓР СР С•РЎвЂљРЎР‚Р С‘РЎвЂљР Вµ Р Р…Р В° Р С”РЎР‚Р С‘РЎРѓРЎвЂљР В°Р В»РЎРЉР Р…Р С• РЎвЂЎР С‘РЎРѓРЎвЂљРЎС“РЎР‹ Р Р†Р С•Р Т‘РЎС“. 
              Р В РЎРЏР Т‘Р С•Р С РЎРѓ Р вЂ™Р В°Р СР С‘ РЎРѓР С‘Р Т‘Р С‘РЎвЂљ РЎР‚РЎвЂ№Р В±Р В°Р С”, РЎРѓ Р В±Р С•Р В»РЎРЉРЎв‚¬Р С‘Р С Р С”Р С•Р В»Р С‘РЎвЂЎР ВµРЎРѓРЎвЂљР Р†Р С•Р С Р С—Р С•Р С”Р ВµР В±Р С•Р В»Р С•Р Р† Р С•Р С”Р С•Р В»Р С• Р Р…Р ВµР С–Р С•.';
    $pers = '<a href="/game.php?go=char&person=1">Р В РЎвЂ№Р В±Р В°Р С”</a>';
    $move = '<a href="/game.php?go=charWork&loc=19" target="_chat_two">Р вЂќР С•РЎР‚Р С•Р С–Р В° 4</a> | 
             <a href="/game.php?go=charWork&loc=22" target="_chat_two">Р В¦Р ВµРЎР‚РЎС“Р В»Р С‘Р Р…</a>';
if(!empty($_GET['person']) && $_GET['person'] == 1){
  $quest_isset_const = 1; 
  $name  = 'Р В РЎвЂ№Р В±Р В°Р С”';
  $about = 'Р ВР Т‘Р С‘ Р С•РЎвЂљРЎРѓРЎР‹Р Т‘Р В°! Р СњР Вµ Р СР ВµРЎв‚¬Р В°Р в„– Р СР Р…Р Вµ РЎР‚РЎвЂ№Р В±Р В°РЎвЂЎР С‘РЎвЂљРЎРЉ.';
  $pers  = '<a href="/game.php?go=char">Р Р€Р в„–РЎвЂљР С‘.</a>';
  $move  = false;
}
?>
<script type="text/javascript"> (function (w, d) { function ajaxGET(url, cb){var x=new XMLHttpRequest();x.open('GET',url,true); try{x.setRequestHeader('X-Requested-With','XMLHttpRequest');}catch(e){} x.onreadystatechange=function(){if(x.readyState===4){var r=null;try{r=JSON.parse(x.responseText);}catch(e){}cb(r,x.status);}}; x.send(null); } function sameOrigin(url){var a=d.createElement('a');a.href=url;return a.host===w.location.host;} function quickGo(href){ w.location.replace(href); } d.addEventListener('click', function(e){ if (e.defaultPrevented || e.button!==0 || e.metaKey||e.ctrlKey||e.shiftKey||e.altKey) return; var a=e.target; while(a && a.tagName!=='A') a=a.parentNode; if(!a||!a.getAttribute) return; var href=a.getAttribute('href')||''; if(!href) return; if(!sameOrigin(href)) return; if (!/\/game\.php\?/.test(href)) return; if (/\bgo=charWork\b/i.test(href)) { e.preventDefault ? e.preventDefault() : (e.returnValue=false); var url = href + (href.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url, function(r){ if (r && r.ok && r.redirect) quickGo(r.redirect); else quickGo('/game.php?go=map'); }); return; } if (/\bgo=map\b/i.test(href) && (/\bgets=/.test(href) || /\bnapadenie=/.test(href))) { e.preventDefault ? e.preventDefault() : (e.returnValue=false); var url2 = href + (href.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url2, function(r){ quickGo('/game.php?go=map'); }); return; } }, true); var _orig_loc = w.loc; function _loc(u){ if (typeof u!=='string'){ if(_orig_loc) try{_orig_loc(u);}catch(e){} return; } if (/^charWork(\b|&)/i.test(u) || /\bgo=charWork\b/i.test(u)){ var full = /^go=/.test(u) ? ('/game.php?'+u) : ('/game.php?go='+u); var url = full + (full.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url, function(r){ if(r&&r.ok&&r.redirect) quickGo(r.redirect); else quickGo('/game.php?go=map'); }); return; } quickGo(/^go=/.test(u)?('/game.php?'+u):('/game.php?go='+u)); } w.loc = _loc; try{ if(w.parent) w.parent.loc = _loc; }catch(e){} try{ if(w.top) w.top.loc=_loc; }catch(e){} })(window, document); </script>
