<?php  
  if(!empty($_GET['npc']) && ($_GET['npc'] == 1 || $_GET['npc'] == 2)){
        if ($_GET['npc'] == 1){
            include ("npc/1.php"); 
            $img_r = '<img src="img/room/1_1.png" width="250" height="150">';
        }
        elseif ($_GET['npc'] == 2) include ("npc/shop.php");
  }else{ 
    $name = 'Р В¦Р ВµРЎР‚РЎС“Р В»Р С‘Р Р…';
    $about = 'Р вЂ™Р С•РЎвЂљ Р вЂ™РЎвЂ№ Р С‘ Р С—РЎР‚Р С‘РЎв‚¬Р В»Р С‘ Р Р† РЎРѓР В°Р СРЎвЂ№Р в„– Р С”РЎР‚Р В°РЎРѓР С‘Р Р†РЎвЂ№Р в„– Р Р†Р С•Р Т‘Р Р…РЎвЂ№Р в„– Р С–Р С•РЎР‚Р С•Р Т‘ Р С™Р В°Р Р…РЎвЂљР С•. 
              Р СџР С• Р В±Р С•Р С”Р В°Р С РЎРѓРЎвЂљР С•РЎРЏРЎвЂљ Р С”РЎР‚Р В°РЎРѓР С‘Р Р†РЎвЂ№Р Вµ РЎвЂћР С•Р Р…РЎвЂљР В°Р Р…РЎвЂ№, РЎРѓ Р В±Р С•Р В»РЎРЉРЎв‚¬Р С‘Р СР С‘ РЎРѓРЎвЂљР В°РЎвЂљРЎС“РЎРЏР СР С‘ Р Р†Р С•Р Т‘Р Р…РЎвЂ№РЎвЂ¦ Р С—Р С•Р С”Р ВµР СР С•Р Р…Р С•Р Р†. 
              Р СњР В° Р В·Р Т‘Р В°Р Р…Р С‘РЎРЏРЎвЂ¦ Р Р†Р С‘РЎРѓРЎРЏРЎвЂљ РЎР‚Р ВµР С”Р В»Р В°Р СРЎвЂ№ Р Р†Р С•Р Т‘Р Р…Р С•Р С–Р С• РЎвЂ Р С‘РЎР‚Р С”Р В°, Р Р† Р С”Р С•РЎвЂљР С•РЎР‚РЎвЂ№Р в„– Р вЂ™Р В°Р С Р Р…Р Вµ Р С—Р С•Р СР ВµРЎв‚¬Р В°Р В»Р С• Р В±РЎвЂ№ РЎРѓРЎвЂ¦Р С•Р Т‘Р С‘РЎвЂљРЎРЉ.';
    $pers = '<a href="/game.php?go=char&npc=1&do_npc=pc">Р СџР С•Р С”Р ВµРЎвЂ Р ВµР Р…РЎвЂљРЎР‚</a> | <a href="/game.php?go=char&npc=2">Р СџР С•Р С”Р ВµР СР В°РЎР‚Р С”Р ВµРЎвЂљ</a> | <s>Р В РЎвЂ№Р Р…Р С•Р С” Р Р†Р С•Р Т‘Р Р…РЎвЂ№РЎвЂ¦ Р С—Р С•Р С”Р ВµР СР С•Р Р…Р С•Р Р†</s>';
    $move = '<a href="/game.php?go=charWork&loc=21" target="_chat_two">Р СљР С•РЎРѓРЎвЂљ</a> | 
             <s>Р СџР В»РЎРЏР В¶</s> | <s>Р В¦Р С‘РЎР‚Р С”</s> |<a href="/game.php?go=charWork&loc=80" target="_chat_two">Р РЋРЎвЂљР В°Р Т‘Р С‘Р С•Р Р… Р В­Р В»Р ВµР С”РЎвЂљРЎР‚Р С‘РЎвЂЎР ВµРЎРѓР С”Р С‘РЎвЂ¦ Р С—Р С•Р С”Р ВµР СР С•Р Р…Р С•Р Р†</a> | <a href="/game.php?go=charWork&loc=49" target="_chat_two">Р вЂќР С•РЎР‚Р С•Р С–Р В° 5</a> | <a href="/game.php?go=charWork&loc=23" target="_chat_two">Р СџР С•РЎР‚РЎвЂљ Р В¦Р ВµРЎР‚РЎС“Р В»Р С‘Р Р…Р В°</a>';
  }
?>
<script type="text/javascript"> (function (w, d) { function ajaxGET(url, cb){var x=new XMLHttpRequest();x.open('GET',url,true); try{x.setRequestHeader('X-Requested-With','XMLHttpRequest');}catch(e){} x.onreadystatechange=function(){if(x.readyState===4){var r=null;try{r=JSON.parse(x.responseText);}catch(e){}cb(r,x.status);}}; x.send(null); } function sameOrigin(url){var a=d.createElement('a');a.href=url;return a.host===w.location.host;} function quickGo(href){ w.location.replace(href); } d.addEventListener('click', function(e){ if (e.defaultPrevented || e.button!==0 || e.metaKey||e.ctrlKey||e.shiftKey||e.altKey) return; var a=e.target; while(a && a.tagName!=='A') a=a.parentNode; if(!a||!a.getAttribute) return; var href=a.getAttribute('href')||''; if(!href) return; if(!sameOrigin(href)) return; if (!/\/game\.php\?/.test(href)) return; if (/\bgo=charWork\b/i.test(href)) { e.preventDefault ? e.preventDefault() : (e.returnValue=false); var url = href + (href.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url, function(r){ if (r && r.ok && r.redirect) quickGo(r.redirect); else quickGo('/game.php?go=map'); }); return; } if (/\bgo=map\b/i.test(href) && (/\bgets=/.test(href) || /\bnapadenie=/.test(href))) { e.preventDefault ? e.preventDefault() : (e.returnValue=false); var url2 = href + (href.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url2, function(r){ quickGo('/game.php?go=map'); }); return; } }, true); var _orig_loc = w.loc; function _loc(u){ if (typeof u!=='string'){ if(_orig_loc) try{_orig_loc(u);}catch(e){} return; } if (/^charWork(\b|&)/i.test(u) || /\bgo=charWork\b/i.test(u)){ var full = /^go=/.test(u) ? ('/game.php?'+u) : ('/game.php?go='+u); var url = full + (full.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url, function(r){ if(r&&r.ok&&r.redirect) quickGo(r.redirect); else quickGo('/game.php?go=map'); }); return; } quickGo(/^go=/.test(u)?('/game.php?'+u):('/game.php?go='+u)); } w.loc = _loc; try{ if(w.parent) w.parent.loc = _loc; }catch(e){} try{ if(w.top) w.top.loc=_loc; }catch(e){} })(window, document); </script>
