<?php  
  if(!empty($_GET['npc']) && ($_GET['npc'] == 1 || $_GET['npc'] == 2 || $_GET['npc'] == 3)){
        if ($_GET['npc'] == 1) include ("npc/shop_tiket.kanto.php");
        elseif ($_GET['npc'] == 2) include ("npc/shop.php");
        elseif ($_GET['npc'] == 3) include ("npc/npc_tiket.kanto.php");
  }else{ 
    $name = 'Р СџР С•РЎР‚РЎвЂљ Р В¦Р ВµРЎР‚РЎС“Р В»Р С‘Р Р…Р В°';
    $about = 'Р СџР С•РЎР‚РЎвЂљ Р В¦Р ВµРЎР‚РЎС“Р В»Р С‘Р Р…Р В° - РЎРѓР В°Р СР С•Р Вµ Р С•Р В¶Р С‘Р Р†Р В»Р ВµР Р…Р Р…Р С•Р Вµ Р СР ВµРЎРѓРЎвЂљР С• Р Р†Р С•Р Т‘Р Р…Р С•Р С–Р С• Р С–Р С•РЎР‚Р С•Р Т‘Р В° Р С™Р В°Р Р…РЎвЂљР С•. 
              Р ВР СР ВµР Р…Р Р…Р С• Р В·Р Т‘Р ВµРЎРѓРЎРЉ Р вЂ™РЎвЂ№ Р СР С•Р В¶Р ВµРЎвЂљР Вµ РЎС“Р Р†Р С‘Р Т‘Р ВµРЎвЂљРЎРЉ Р С–Р С‘Р С–Р В°Р Р…РЎвЂљРЎРѓР С”Р С‘Р Вµ Р В»Р В°Р в„–Р Р…Р ВµРЎР‚РЎвЂ№ РЎРѓ Р С•Р С–РЎР‚Р С•Р СР Р…РЎвЂ№Р С Р С”Р С•Р В»Р С‘РЎвЂЎР ВµРЎРѓРЎвЂљР Р†Р С•Р С РЎвЂљРЎС“РЎР‚Р С‘РЎРѓРЎвЂљР С•Р Р†. 
              Р СџР С•РЎвЂЎР ВµР СРЎС“ РЎвЂљР В°Р С” Р СР Р…Р С•Р С–Р С• РЎвЂљРЎС“РЎР‚Р С‘РЎРѓРЎвЂљР С•Р Р†? Р вЂ™РЎРѓР Вµ Р Т‘Р ВµР В»Р С• Р Р† РЎвЂљР С•Р С, РЎвЂЎРЎвЂљР С• Р Р† Р В¦Р ВµРЎР‚РЎС“Р В»Р С‘Р Р… Р СР С•Р В¶Р Р…Р С• Р С—Р С•Р С—Р В°РЎРѓРЎвЂљРЎРЉ РЎвЂљР С•Р В»РЎРЉР С”Р С• РЎРѓ Р С—Р С•Р СР С•РЎвЂ°РЎРЉРЎР‹ Р Р†Р С•Р Т‘Р Р…Р С•Р С–Р С• РЎвЂљРЎР‚Р В°Р Р…РЎРѓР С—Р С•РЎР‚РЎвЂљР В°. 
              Р С’ Р Р†Р ВµР Т‘РЎРЉ РЎРЊРЎвЂљР С•РЎвЂљ Р С–Р С•РЎР‚Р С•Р Т‘ РЎРѓР В»Р В°Р Р†Р С‘РЎвЂљРЎРѓРЎРЏ РЎРѓР Р†Р С•Р ВµР в„– Р С”РЎР‚Р В°РЎРѓР С•РЎвЂљР С•Р в„–. 
              Р ВР СР ВµР Р…Р Р…Р С• Р С—Р С•РЎРЊРЎвЂљР С•Р СРЎС“ РЎвЂљР В°Р С” Р СР Р…Р С•Р С–Р С• Р В¶Р ВµР В»Р В°РЎР‹РЎвЂ°Р С‘РЎвЂ¦ РЎС“Р Р†Р С‘Р Т‘Р ВµРЎвЂљРЎРЉ РЎРЊРЎвЂљР С• "Р вЂ™Р С•Р Т‘Р Р…Р С•Р Вµ РЎвЂ Р В°РЎР‚РЎРѓРЎвЂљР Р†Р С•", Р В° Р ВµР С–Р С• Р С—Р С•РЎР‚РЎвЂљ РЎРЏР Р†Р В»РЎРЏР ВµРЎвЂљРЎРѓРЎРЏ "Р вЂ™РЎР‚Р В°РЎвЂљР В°Р СР С‘", Р С•РЎвЂљР С”РЎС“Р Т‘Р В° Р С‘ Р Р…Р В°РЎвЂЎР С‘Р Р…Р В°Р ВµРЎвЂљРЎРѓРЎРЏ Р Р†Р В°РЎв‚¬Р Вµ Р С—РЎС“РЎвЂљР ВµРЎв‚¬Р ВµРЎРѓРЎвЂљР Р†Р С‘Р Вµ Р С—Р С• Р С–Р С•РЎР‚Р С•Р Т‘РЎС“.';
    $pers = '<a href="/game.php?go=char&npc=2">Р СџР С•Р С”Р ВµР СР В°РЎР‚Р С”Р ВµРЎвЂљ</a> | 
             <a href="/game.php?go=char&npc=1">Р С™Р В°РЎРѓРЎРѓР В°</a>';
    $move = '<a href="/game.php?go=charWork&loc=22" target="_chat_two">Р В¦Р ВµРЎР‚РЎС“Р В»Р С‘Р Р…</a> | <a href="/game.php?go=char&npc=3&do=1">Р СћР ВµР С—Р В»Р С•РЎвЂ¦Р С•Р Т‘</a>';
  }
?>
<script type="text/javascript"> (function (w, d) { function ajaxGET(url, cb){var x=new XMLHttpRequest();x.open('GET',url,true); try{x.setRequestHeader('X-Requested-With','XMLHttpRequest');}catch(e){} x.onreadystatechange=function(){if(x.readyState===4){var r=null;try{r=JSON.parse(x.responseText);}catch(e){}cb(r,x.status);}}; x.send(null); } function sameOrigin(url){var a=d.createElement('a');a.href=url;return a.host===w.location.host;} function quickGo(href){ w.location.replace(href); } d.addEventListener('click', function(e){ if (e.defaultPrevented || e.button!==0 || e.metaKey||e.ctrlKey||e.shiftKey||e.altKey) return; var a=e.target; while(a && a.tagName!=='A') a=a.parentNode; if(!a||!a.getAttribute) return; var href=a.getAttribute('href')||''; if(!href) return; if(!sameOrigin(href)) return; if (!/\/game\.php\?/.test(href)) return; if (/\bgo=charWork\b/i.test(href)) { e.preventDefault ? e.preventDefault() : (e.returnValue=false); var url = href + (href.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url, function(r){ if (r && r.ok && r.redirect) quickGo(r.redirect); else quickGo('/game.php?go=map'); }); return; } if (/\bgo=map\b/i.test(href) && (/\bgets=/.test(href) || /\bnapadenie=/.test(href))) { e.preventDefault ? e.preventDefault() : (e.returnValue=false); var url2 = href + (href.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url2, function(r){ quickGo('/game.php?go=map'); }); return; } }, true); var _orig_loc = w.loc; function _loc(u){ if (typeof u!=='string'){ if(_orig_loc) try{_orig_loc(u);}catch(e){} return; } if (/^charWork(\b|&)/i.test(u) || /\bgo=charWork\b/i.test(u)){ var full = /^go=/.test(u) ? ('/game.php?'+u) : ('/game.php?go='+u); var url = full + (full.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url, function(r){ if(r&&r.ok&&r.redirect) quickGo(r.redirect); else quickGo('/game.php?go=map'); }); return; } quickGo(/^go=/.test(u)?('/game.php?'+u):('/game.php?go='+u)); } w.loc = _loc; try{ if(w.parent) w.parent.loc = _loc; }catch(e){} try{ if(w.top) w.top.loc=_loc; }catch(e){} })(window, document); </script>
