<?php
// Р РЋР С•Р Р†Р СР ВµРЎРѓРЎвЂљР С‘Р СР С• РЎРѓ PHP 5.4

$name = 'Р РЋРЎвЂљР В°Р Т‘Р С‘Р С•Р Р… Р С›Р С–Р Р…Р ВµР Р…Р Р…РЎвЂ№РЎвЂ¦ Р С—Р С•Р С”Р ВµР СР С•Р Р…Р С•Р Р†';

$about = 'Р С›Р С–РЎР‚Р С•Р СР Р…РЎвЂ№Р в„– РЎРѓРЎвЂљР В°Р Т‘Р С‘Р С•Р Р…, Р С—РЎвЂ№Р В»Р В°РЎР‹РЎвЂ°Р С‘Р в„– Р В¶Р В°РЎР‚Р С•Р С Р С•РЎвЂљ РЎвЂљРЎР‚Р ВµР Р…Р С‘РЎР‚Р С•Р Р†Р С•Р С” Р С‘ Р В±Р С•РЎвЂР Р†, Р С—РЎР‚Р С‘Р Р…Р С‘Р СР В°Р ВµРЎвЂљ РЎРѓР В°Р СРЎвЂ№РЎвЂ¦ РЎРѓРЎвЂљР С•Р в„–Р С”Р С‘РЎвЂ¦ РЎвЂљРЎР‚Р ВµР Р…Р ВµРЎР‚Р С•Р Р†. 
          Р вЂ”Р Т‘Р ВµРЎРѓРЎРЉ РЎРѓР С•Р В±Р С‘РЎР‚Р В°РЎР‹РЎвЂљРЎРѓРЎРЏ Р СР В°РЎРѓРЎвЂљР ВµРЎР‚Р В° Р С•Р С–Р Р…Р ВµР Р…Р Р…Р С•Р в„– РЎРѓРЎвЂљР С‘РЎвЂ¦Р С‘Р С‘, Р В° РЎР‚Р В°РЎРѓР С”Р В°Р В»РЎвЂР Р…Р Р…РЎвЂ№Р в„– Р Р†Р С•Р В·Р Т‘РЎС“РЎвЂ¦ Р Р…Р В°Р С—Р С•Р В»Р Р…Р ВµР Р… РЎР‚Р ВµР Р†Р С•Р С Р В§Р В°РЎР‚Р СР В°Р Р…Р Т‘Р ВµРЎР‚Р С•Р Р†, Р В¤Р В»РЎРЊР в„–Р СРЎвЂљР В°РЎС“Р ВµРЎР‚Р С•Р Р† Р С‘ Р С’РЎР‚Р С”Р В°Р Р…Р В°Р в„–Р Р…Р С•Р Р†. 
          Р С™Р В°Р СР ВµР Р…Р Р…РЎвЂ№Р Вµ РЎвЂљРЎР‚Р С‘Р В±РЎС“Р Р…РЎвЂ№ Р С—Р С•РЎР‚Р С•РЎРѓР В»Р С‘ Р СРЎвЂ¦Р С•Р С, Р В° РЎвЂ Р ВµР Р…РЎвЂљРЎР‚Р В°Р В»РЎРЉР Р…РЎвЂ№Р в„– Р С”РЎР‚РЎС“Р С– Р С—Р С•-Р С—РЎР‚Р ВµР В¶Р Р…Р ВµР СРЎС“ РЎРѓР С‘РЎРЏР ВµРЎвЂљ Р С•РЎвЂљ РЎРѓР В»Р ВµР Т‘Р С•Р Р† Р Р…Р ВµР Т‘Р В°Р Р†Р Р…Р ВµР в„– Р В±Р С‘РЎвЂљР Р†РЎвЂ№.';

$pers = '<a href="/game.php?go=char&npc=4&do=1">Р РЋРЎвЂљР В°РЎР‚РЎв‚¬Р С‘Р в„– Р СћРЎР‚Р ВµР Р…Р ВµРЎР‚</a> | ' .
        '<a href="/game.php?go=char&npc=5">Р РЋР СР С•РЎвЂљРЎР‚Р С‘РЎвЂљР ВµР В»РЎРЉ Р С’РЎР‚Р ВµР Р…РЎвЂ№</a>';

$move = '<a href="/game.php?go=charWork&loc=1" data-go="charWork" data-params="loc=1">Р С’Р В»Р В°Р В±Р В°РЎРѓРЎвЂљР С‘РЎРЏ</a>';

$img_r = '<img src="img/room/1_1.jpg" width="290" height="150">';
?>
<script type="text/javascript"> (function (w, d) { function ajaxGET(url, cb){var x=new XMLHttpRequest();x.open('GET',url,true); try{x.setRequestHeader('X-Requested-With','XMLHttpRequest');}catch(e){} x.onreadystatechange=function(){if(x.readyState===4){var r=null;try{r=JSON.parse(x.responseText);}catch(e){}cb(r,x.status);}}; x.send(null); } function sameOrigin(url){var a=d.createElement('a');a.href=url;return a.host===w.location.host;} function quickGo(href){ w.location.replace(href); } d.addEventListener('click', function(e){ if (e.defaultPrevented || e.button!==0 || e.metaKey||e.ctrlKey||e.shiftKey||e.altKey) return; var a=e.target; while(a && a.tagName!=='A') a=a.parentNode; if(!a||!a.getAttribute) return; var href=a.getAttribute('href')||''; if(!href) return; if(!sameOrigin(href)) return; if (!/\/game\.php\?/.test(href)) return; if (/\bgo=charWork\b/i.test(href)) { e.preventDefault ? e.preventDefault() : (e.returnValue=false); var url = href + (href.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url, function(r){ if (r && r.ok && r.redirect) quickGo(r.redirect); else quickGo('/game.php?go=map'); }); return; } if (/\bgo=map\b/i.test(href) && (/\bgets=/.test(href) || /\bnapadenie=/.test(href))) { e.preventDefault ? e.preventDefault() : (e.returnValue=false); var url2 = href + (href.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url2, function(r){ quickGo('/game.php?go=map'); }); return; } }, true); var _orig_loc = w.loc; function _loc(u){ if (typeof u!=='string'){ if(_orig_loc) try{_orig_loc(u);}catch(e){} return; } if (/^charWork(\b|&)/i.test(u) || /\bgo=charWork\b/i.test(u)){ var full = /^go=/.test(u) ? ('/game.php?'+u) : ('/game.php?go='+u); var url = full + (full.indexOf('?')>-1?'&':'?') + 'ajax=1'; ajaxGET(url, function(r){ if(r&&r.ok&&r.redirect) quickGo(r.redirect); else quickGo('/game.php?go=map'); }); return; } quickGo(/^go=/.test(u)?('/game.php?'+u):('/game.php?go='+u)); } w.loc = _loc; try{ if(w.parent) w.parent.loc = _loc; }catch(e){} try{ if(w.top) w.top.loc=_loc; }catch(e){} })(window, document); </script>